### ISSUE TITLE
Equations in latex dont render properly

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/train-schedule-optimisation-challenge-starter-kit#1]
Example : https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/documentation/business_rules.md#objective-function

**Comment by scarroll32** [comment]
Long running thread on this here: https://github.com/github/markup/issues/897#issuecomment-231591884

**Comment by jordiju** [comment]
Shame, was really nice over on gitlab. 

I don't really like the codecogs-solution, and that website is actually blocked by our enterprise proxy for potential security risks.

What about if we just paste in screenshots? It's not pretty, but a quick fix that works.

Anybody have better suggestions?

**Comment by spMohanty** [comment]
@jordiju : Lets move all this content to ipython notebooks ?
That way we could also include executable code, and happily embed latex.

Something along the lines of : https://github.com/crowdAI/mapping-challenge-starter-kit/blob/master/Dataset%20Utils.ipynb

**Comment by jordiju** [comment]
Ah, much better. We will do that today.

**Comment by jordiju** [comment]
By "we", I mean me or Raphael ;)

**Comment by rapsli** [comment]
Jupyter Notebook was having issues with linking images. Moved everything to Markdown and added inserted the formula in an image. #7
