### ISSUE TITLE
yEd graphs don't work

### ISSUE THREAD

**Issue by hurbutun** [crowdAI/train-schedule-optimisation-challenge-starter-kit#11]
Hello,

I was trying to visualise the routes in '01_dummy.json' using 'route_graph.py' but I got the following error on yEd:
'The attribute label is of type long which is currently not supported. lts data was converted to integers and some values might have been truncated. '

Afterwards yEd opens a sheet with only one box in it. Could you please check it?

**Comment by rapsli** [comment]
@hurbutun thanks for reaching out. Can you please let me know the version of python you are using?

**Comment by hurbutun** [comment]
I use python 3.6.3 with PyCharm 2018.1.2

**Comment by rapsli** [comment]
We had someone else with an issue (https://www.crowdai.org/topics/route_graph-py-error/discussion). Can you try upping your dependencies. I am currently using:

networkx==2.1
matplotlib==2.2.2

**Comment by hurbutun** [comment]
Sorry I hadn't noticed the topic there. In fact I haven't checked the discussion forum since I thought we were supposed to use github for technical issues.

My matplotlib was 2.1.x I just upgraded to the latest version (2.2.3) using pip but it didn't solve the issue. Any other recommendations?

**Comment by rapsli** [comment]
What platform are you using and on which line does the error occur?

**Comment by hurbutun** [comment]
I am not sure if I understand what you mean by platform.

I am using:
macOS 10.13.6 high sierra
PyCharm 2018.1.2
yEd 3.17.2

I gave the information about the python related stuff above. The python script works without any error/warning message. Afterwards when I try to open the .graphml file I get the message in my first post above 3 times. When I click ok or close the message box on yEd all I can see is a single box.

**Comment by rapsli** [comment]
Sorry. I misunderstood your question. I will try myself and will get back to you.

**Comment by rapsli** [comment]
Ok, same behaviour in the download version.
I have successfully tested in on the online version: https://www.yworks.com/yed-live/

I will have a look and see if I can fix the offline version as well in the meantime please use the browser version.

**Comment by hurbutun** [comment]
thanks, indeed it looks like the online version seems to work

**Comment by rapsli** [comment]
I have investigated on the offline version. It actually works as well. It's just not showing them upon startup. You have to tell yEd to layout the nodes.... that graph is rather unspectacular ;)

![image](https://user-images.githubusercontent.com/366040/45692561-5e1a4c80-bb5b-11e8-9561-9fe8fde407dc.png)

**Comment by hurbutun** [comment]
oh, my bad sorry. Thanks a lot for the help!

**Comment by rapsli** [comment]
good luck with the challenge.
