### ISSUE TITLE
Add an example submission file 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/train-schedule-optimisation-challenge-starter-kit#2]
Adding a sample submission file will act as a good reference for participants.
And they can also try submitting it right away and claim atleast a spot on the leaderboard.

**Comment by jordiju** [comment]
There is one [here](https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/problem_instances/sample_solutions/sample_submission.json). 

It is also used in [what to submit](https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/documentation/what_to_submit.md)
