### ISSUE TITLE
Images not rendered / link wrong?

### ISSUE THREAD

**Issue by jordiju** [crowdAI/train-schedule-optimisation-challenge-starter-kit#4]
The images are not shown in most markdowns in the documentation folder

Example

* [business rules](https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/documentation/business_rules.md#example-1-no-delay)
* input data model

In [worked example](https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/blob/master/documentation/a_worked_example.md) they work.

--> Link must be realtive to location of the markdown, remove the 'documentation/' from the relative path (on gitlab, the path had to be relative to the repo root)

**Comment by scarroll32** [comment]
Fixed by https://github.com/crowdAI/train-schedule-optimisation-challenge-starter-kit/pull/6
