### ISSUE TITLE
Submission Page does not work (500)

### ISSUE THREAD

**Issue by jordiju** [crowdAI/train-schedule-optimisation-challenge-starter-kit#5]
I get this when I try to open the "Submission" Tab

![image](https://user-images.githubusercontent.com/37622418/43882718-09e6ba3c-9bb1-11e8-9324-8407f2fdc069.png)

**Comment by scarroll32** [comment]
[Moved to crowdAI repo](https://github.com/crowdAI/crowdai/issues/913)
