### ISSUE TITLE
New Topics on the Discussion Page do not trigger Email notification

### ISSUE THREAD

**Issue by jordiju** [crowdAI/train-schedule-optimisation-challenge-starter-kit#9]
When someone opens a new topic on the [Challenge Discussion](https://www.crowdai.org/challenges/train-schedule-optimisation-challenge/topics) page, I don't receive a notification. Only on subsequent comments on the same topic do I get notified.

The notification ought to be triggered also by opening a new topic.

**Comment by spMohanty** [comment]
@seanfcarroll : This has been an open issue for quite some time. 
We should probably deal with this issue with a high priority.

**Comment by scarroll32** [comment]
No, I don't think there is an existing issue for this problem. 

I've now opened one [here](https://github.com/crowdAI/crowdai/issues/928) and will get to it asap.

This issue is moved to the crowdAI repo.
